# vsgame_exp01 Statistics
## Agency broadly enhances memory beyond directly controlled information
### Tej Bhoga, Zachariah M. Reagh, and Angelique I. Delarazan

## Set Up

### Import Packages

In [1]:
import matplotlib.pyplot as plt
import glob
import os
import pandas as pd
import re
import seaborn as sns
import itertools
import statsmodels.api as sm 
import statsmodels.formula.api as smf
# import ptitprince as pt

### Load Data

In [2]:
base_dir = '/Users/aidelarazan/Box Sync/aidelarazan_box/Projects/vsgame/exp01/data/'
mst = pd.read_csv(os.path.join(base_dir, 'vsgame_exp01_sub-all_task-MST.csv'))
spatial_placement = pd.read_csv(os.path.join(base_dir, 'vsgame_exp01_sub-all_task-SpatialPlacement.csv'))
item_desc = pd.read_csv(os.path.join(base_dir, 'vsgame_exp01_sub-all_task-ItemRecallDescriptions_desc-SemanticSimilarity.csv'))
questionnaire = pd.read_csv(os.path.join(base_dir, 'vsgame_exp01_sub-all_task-PostTaskSurvey.csv'))
demographics = pd.read_csv(os.path.join(base_dir, 'vsgame_exp01_sub-all_task-Demographics.csv'))
excluded_subjects = [152, 161]

## MST

In [3]:
mst.head()

,subject,condition,experiment,task,target_hit,target_miss,lure_cr,lure_fa,foil_cr,foil_fa,...,fa_rate,dprime,dprime_lures,LDI,LDI_reviewer,beta,c,ad,foiled_target,foiled_lure
0,121,Active,exp01,mst,18,3,13,8,24,0,...,0.163265,2.619676,1.050540,0.40,NaN,1.365406,0.199142,0.968015,3,4
1,120,Active,exp01,mst,19,1,12,9,22,2,...,0.224490,2.089297,1.064761,0.44,NaN,1.037882,0.025407,0.930210,1,4
2,122,Active,exp01,mst,13,9,2,14,23,1,...,0.306122,1.781818,-0.100816,-0.28,NaN,1.135646,0.228359,0.896154,9,9
3,123,Active,exp01,mst,12,4,14,9,19,5,...,0.285714,0.762064,0.308305,0.40,NaN,1.172211,0.308051,0.705009,4,2
4,124,Active,exp01,mst,6,3,14,9,21,3,...,0.244898,0.444047,-0.347844,0.44,NaN,0.989115,0.698468,0.623235,3,2

In [4]:
mst = mst.dropna(subset=['dprime', 'condition', 'subject']).reset_index(drop=True)
mst = mst[~mst['subject'].isin(excluded_subjects)].reset_index(drop=True)
mst

,subject,condition,experiment,task,target_hit,target_miss,lure_cr,lure_fa,foil_cr,foil_fa,...,fa_rate,dprime,dprime_lures,LDI,LDI_reviewer,beta,c,ad,foiled_target,foiled_lure
0,121,Active,exp01,mst,18,3,13,8,24,0,...,0.163265,2.619676,1.050540,0.40,NaN,1.365406,0.199142,0.968015,3,4
1,120,Active,exp01,mst,19,1,12,9,22,2,...,0.224490,2.089297,1.064761,0.44,NaN,1.037882,0.025407,0.930210,1,4
2,122,Active,exp01,mst,13,9,2,14,23,1,...,0.306122,1.781818,-0.100816,-0.28,NaN,1.135646,0.228359,0.896154,9,9
3,123,Active,exp01,mst,12,4,14,9,19,5,...,0.285714,0.762064,0.308305,0.40,NaN,1.172211,0.308051,0.705009,4,2
4,124,Active,exp01,mst,6,3,14,9,21,3,...,0.244898,0.444047,-0.347844,0.44,NaN,0.989115,0.698468,0.623235,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,264,Passive,exp01,mst,13,4,7,8,22,2,...,0.204082,1.433148,0.517852,0.12,NaN,1.406092,0.388488,0.844563,4,10
84,265,Passive,exp01,mst,17,7,4,14,24,0,...,0.285714,2.504533,0.316730,-0.12,NaN,1.052089,0.049125,0.961717,7,7
85,266,Passive,exp01,mst,16,8,2,13,24,0,...,0.265306,2.395293,0.308305,-0.24,NaN,1.141523,0.134306,0.954841,8,10
86,267,Passive,exp01,mst,9,13,3,9,24,0,...,0.183673,1.678375,0.000000,-0.40,NaN,1.407850,0.629956,0.882345,13,13
87,260,Passive,exp01,mst,13,11,1,6,23,1,...,0.142857,1.781818,0.756456,-0.40,NaN,1.765786,0.508708,0.896154,11,18

### dprime

In [5]:
mst.groupby('condition')['dprime'].describe().reset_index()

,condition,count,mean,std,min,25%,50%,75%,max
0,Active,44.0,2.284411,0.689791,0.444047,1.783070,2.343500,2.878455,3.787520
1,Passive,44.0,1.491314,0.927005,-0.889824,0.876865,1.679943,2.187803,3.031292

In [6]:
model = smf.ols("dprime ~ condition", data=mst).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 dprime   R-squared:                       0.194
Model:                            OLS   Adj. R-squared:                  0.185
Method:                 Least Squares   F-statistic:                     20.73
Date:                Tue, 18 Aug 2026   Prob (F-statistic):           1.73e-05
Time:                        14:14:30   Log-Likelihood:                -106.07
No. Observations:                  88   AIC:                             216.1
Df Residuals:                      86   BIC:                             221.1
Df Model:                           1
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                2.2844      0.123     18.546      0.000       2.040       2.529
condition[T.Passive]    -0.7931      0.174     -4.553      0.000      -1.139      -0.447
==============================================================================
Omnibus:                        7.212   Durbin-Watson:                   2.154
Prob(Omnibus):                  0.027   Jarque-Bera (JB):                6.782
Skew:                          -0.662   Prob(JB):                       0.0337
Kurtosis:                       3.309   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### LDI

In [222]:
mst.groupby('condition')['LDI'].describe().reset_index()

  condition  count      mean       std   min   25%   50%   75%   max
0    Active   44.0  0.243636  0.321487 -0.44  0.00  0.24  0.44  0.96
1   Passive   44.0  0.037273  0.318298 -0.60 -0.15  0.04  0.28  0.60

In [223]:
model = smf.ols("LDI ~ condition", data=mst).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    LDI   R-squared:                       0.096
Model:                            OLS   Adj. R-squared:                  0.086
Method:                 Least Squares   F-statistic:                     9.155
Date:                Mon, 17 Aug 2026   Prob (F-statistic):            0.00327
Time:                        16:45:28   Log-Likelihood:                -23.556
No. Observations:                  88   AIC:                             51.11
Df Residuals:                      86   BIC:                             56.07
Df Model:                           1
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.2436      0.048      5.052      0.000       0.148       0.340
condition[T.Passive]    -0.2064      0.068     -3.026      0.003      -0.342      -0.071
==============================================================================
Omnibus:                        1.851   Durbin-Watson:                   1.469
Prob(Omnibus):                  0.396   Jarque-Bera (JB):                1.359
Skew:                          -0.050   Prob(JB):                        0.507
Kurtosis:                       2.399   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Spatial Placement

In [224]:
spatial_placement = spatial_placement[~spatial_placement['subject'].isin(excluded_subjects)].reset_index(drop=True)
spatial_placement.head()

,subject,condition,experiment,task,item_category,item,response_x,response_y,correct_response_x,correct_response_y,distance
0,121,Active,exp01,spatial_placement,target,alarmclock,345,364,119,361,226.019911
1,121,Active,exp01,spatial_placement,target,applecore,354,355,392,350,38.327536
2,121,Active,exp01,spatial_placement,lure,bikepump,186,310,439,350,256.142538
3,121,Active,exp01,spatial_placement,target,binoculars,134,338,270,339,136.003676
4,121,Active,exp01,spatial_placement,lure,blender,258,135,333,170,82.764727

In [225]:
spatial_placement = spatial_placement.groupby(['subject', 'condition', 'experiment']).mean('distance').reset_index()
spatial_placement = spatial_placement[['subject', 'condition', 'experiment', 'distance']].reset_index(drop=True)
spatial_placement

    subject condition experiment    distance
0       120    Active      exp01  128.701862
1       121    Active      exp01  168.631817
2       122    Active      exp01  160.020865
3       123    Active      exp01  164.448523
4       124    Active      exp01  156.159364
..      ...       ...        ...         ...
83      263   Passive      exp01  105.786710
84      264   Passive      exp01  182.886637
85      265   Passive      exp01  189.021305
86      266   Passive      exp01  195.833308
87      267   Passive      exp01  157.997342

[88 rows x 4 columns]

In [226]:
spatial_placement.groupby('condition')['distance'].describe().reset_index()

,condition,count,mean,std,min,25%,50%,75%,max
0,Active,44.0,150.805166,23.815624,89.183675,132.669817,155.495656,168.634666,193.782235
1,Passive,44.0,149.086831,30.206719,87.238332,129.952602,148.137931,167.100117,209.480554

In [227]:
spatial_placement = spatial_placement.dropna(
    subset=['distance', 'condition', 'subject']
).reset_index(drop=True)
spatial_placement

    subject condition experiment    distance
0       120    Active      exp01  128.701862
1       121    Active      exp01  168.631817
2       122    Active      exp01  160.020865
3       123    Active      exp01  164.448523
4       124    Active      exp01  156.159364
..      ...       ...        ...         ...
83      263   Passive      exp01  105.786710
84      264   Passive      exp01  182.886637
85      265   Passive      exp01  189.021305
86      266   Passive      exp01  195.833308
87      267   Passive      exp01  157.997342

[88 rows x 4 columns]

In [228]:
model = smf.ols("distance ~ condition", data=spatial_placement).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               distance   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.011
Method:                 Least Squares   F-statistic:                   0.08780
Date:                Mon, 17 Aug 2026   Prob (F-statistic):              0.768
Time:                        16:45:29   Log-Likelihood:                -414.54
No. Observations:                  88   AIC:                             833.1
Df Residuals:                      86   BIC:                             838.0
Df Model:                           1
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept              150.8052      4.100     36.777      0.000     142.654     158.957
condition[T.Passive]    -1.7183      5.799     -0.296      0.768     -13.246       9.810
==============================================================================
Omnibus:                        0.511   Durbin-Watson:                   1.619
Prob(Omnibus):                  0.775   Jarque-Bera (JB):                0.645
Skew:                          -0.056   Prob(JB):                        0.724
Kurtosis:                       2.596   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Item Recall Description

In [229]:
item_desc = item_desc[~item_desc['subject'].isin(excluded_subjects)].reset_index(drop=True)
item_desc = item_desc.groupby(['subject', 'condition', 'experiment']).mean('semantic_similarity').reset_index()
item_desc

    subject condition experiment  semantic_similarity
0       120    Active      exp01             0.357643
1       121    Active      exp01             0.550803
2       122    Active      exp01             0.148501
3       123    Active      exp01             0.367485
4       124    Active      exp01             0.385723
..      ...       ...        ...                  ...
83      263   Passive      exp01             0.181157
84      264   Passive      exp01             0.272611
85      265   Passive      exp01             0.412058
86      266   Passive      exp01             0.419876
87      267   Passive      exp01            -0.013803

[88 rows x 4 columns]

In [230]:
item_desc.groupby('condition')['semantic_similarity'].describe().reset_index()

,condition,count,mean,std,min,25%,50%,75%,max
0,Active,44.0,0.345748,0.134295,0.029680,0.284269,0.355188,0.436173,0.589197
1,Passive,44.0,0.261170,0.142393,-0.013803,0.177891,0.265523,0.355556,0.592096

In [231]:
item_desc = pd.merge(item_desc, attention, on=['subject', 'condition'], how='left')
item_desc = item_desc.dropna(
    subset=['semantic_similarity', 'condition', 'subject']
).reset_index(drop=True)
item_desc

,subject,condition,experiment_x,semantic_similarity,Unnamed: 0,response,question,prompt,min,max,experiment_y,task
0,120,Active,exp01,0.357643,1,3.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
1,121,Active,exp01,0.550803,0,0.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
2,122,Active,exp01,0.148501,2,2.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
3,123,Active,exp01,0.367485,3,3.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
4,124,Active,exp01,0.385723,4,4.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
...,...,...,...,...,...,...,...,...,...,...,...,...
83,263,Passive,exp01,0.181157,84,2.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
84,264,Passive,exp01,0.272611,85,5.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
85,265,Passive,exp01,0.412058,86,4.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
86,266,Passive,exp01,0.419876,87,4.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention
87,267,Passive,exp01,-0.013803,88,4.0,attention,How attentive did you feel to the game task?,I felt “in the zone.”,I felt unable to pay attention to the game.,exp01,attention

In [232]:
model = smf.ols("semantic_similarity ~ condition", data=item_desc).fit()
print(model.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     semantic_similarity   R-squared:                       0.087
Model:                             OLS   Adj. R-squared:                  0.077
Method:                  Least Squares   F-statistic:                     8.216
Date:                 Mon, 17 Aug 2026   Prob (F-statistic):            0.00522
Time:                         16:45:31   Log-Likelihood:                 50.172
No. Observations:                   88   AIC:                            -96.34
Df Residuals:                       86   BIC:                            -91.39
Df Model:                            1
Covariance Type:             nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.3457      0.021     16.571      0.000       0.304       0.387
condition[T.Passive]    -0.0846      0.030     -2.866      0.005      -0.143      -0.026
==============================================================================
Omnibus:                        0.681   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.711   Jarque-Bera (JB):                0.786
Skew:                          -0.191   Prob(JB):                        0.675
Kurtosis:                       2.738   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Post-Experiment Survey

In [233]:
questionnaire = questionnaire[~questionnaire['subject'].isin(excluded_subjects)].reset_index(drop=True)
questionnaire.groupby(['question', 'condition'])['response'].agg(['mean', 'std', 'count']).round(2).reset_index()

             question condition  mean   std  count
0   action_prediction   Passive  3.34  1.76     44
1           attention    Active  2.30  1.30     44
2           attention   Passive  3.86  1.17     43
3             control    Active  2.44  1.48     43
4             control   Passive  4.74  1.45     42
5      enc_confidence    Active  2.86  1.71     44
6      enc_confidence   Passive  3.60  1.64     43
7        enc_strategy    Active  2.61  2.12     44
8        enc_strategy   Passive  2.48  1.53     44
9         expectation   Passive  2.77  1.63     44
10    item_prediction   Passive  3.32  2.31     44
11   passive_presence   Passive  4.09  1.83     44
12        perspective    Active  3.11  1.75     44
13        perspective   Passive  3.30  1.81     44
14           presence    Active  3.25  1.69     44
15           presence   Passive  3.91  1.46     44
16         randomness    Active  3.20  1.86     44
17         randomness   Passive  4.52  1.59     44
18     rec_confidence    Active  4.14  1.13     44
19     rec_confidence   Passive  4.23  1.01     44
20       rec_strategy    Active  3.41  1.59     44
21       rec_strategy   Passive  3.63  1.72     43

## Demographics

In [234]:
demographics = demographics[~demographics['Subject'].isin(excluded_subjects)].reset_index(drop=True)

In [235]:
demographics.groupby(['Group'])['Age'].describe().reset_index()

     Group  count       mean       std   min   25%   50%   75%   max
0   Active   45.0  19.311111  1.202691  18.0  18.0  19.0  20.0  22.0
1  Passive   40.0  19.150000  1.166850  18.0  18.0  19.0  20.0  21.0

In [ ]:
demographics.groupby('Group')['Sex'].value_counts()

Group    Sex
Active   Female     30
         Male       15
Passive  Female     24
         Male       15
         female      1
Name: count, dtype: int64